stages:
  - linting
  - formatting
  - testing

flake8:
  stage: linting
  image: registry.gitlab.com/pipeline-components/flake8:latest
  script:
    - pip install -r requirements/test.txt
    - flake8 --verbose --config=.flake8 .

black:
  stage: formatting
  image: registry.gitlab.com/pipeline-components/black:latest
  script:
    - black --check --config .black .

django-tests:
  stage: testing
  image: python:latest
  script:
    - pip install -r requirements/test.txt
    - cd petpreneur
    - python manage.py test